#THIS PROGRAM MAKES CHANGES TO THE COWRIE CONFIG FILE

#1. OPEN THE CONFIG FILE
#2. APPEND LINE TO END OF FILE
#3. CLOSE FILE


#THIS PROGRAM WILL PROVIDE OPTIONS FOR THE USER TO CHOOSE

#OPTION 1 - MIMICRY
#THIS WILL APPEND MIMICRY SETTINGS TO THE CONFIG FILE

#OPTION 2 - USERDB.EXAMPLE FILE WILL BE UPDATED TO HAVE NEW CREDENTIALS